name: "Detect Language"
description: "Detects the programming language of the project based on common files."

outputs:
  language:
    description: "The detected programming language."
    value: ${{steps.detect-language.outputs.language}}
runs:
  using: "composite"
  steps:
    - name: "Path"
      run: echo "$GITHUB_ACTION_PATH/entrypoint.sh"
      shell: bash

    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      id: detect-language
      shell: bash