name: heimdall-findings-validator

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

concurrency: pipeline-define-language

jobs:
  pipeline-define-language:
    runs-on: ${{ inputs.runs-on }}
    env:
      AWS_DEFAULT_REGION: us-east-1
    outputs:
      language: ${{ steps.detect-project-language.outputs.language }}
    steps:
      - name: Clone Application
        uses: actions/checkout@v3

      - name: Detect Project Language
        id: detect-project-language
        uses: Hotmart-Labs/backoffice-actions/actions/detect-language-action@master

  java-findings:
    needs: pipeline-define-language
    if: ${{ needs.pipeline-define-language.outputs.language == 'Java'}}
    uses: Hotmart-Labs/backoffice-actions/.github/workflows/java-action.yml@master
    with:
      runs-on: ${{ inputs.runs-on }}


