name: heimdall-findings-validator

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

jobs:
  define-language:
    runs-on: ${{ inputs.runs-on }}
    env:
      AWS_DEFAULT_REGION: us-east-1
    outputs:
      language: ${{ steps.detect-project-language.outputs.language }}
    steps:
      - name: Clone Application
        uses: actions/checkout@v3

      - name: Detect Project Language
        id: detect-project-language
        uses: Hotmart-Labs/backoffice-actions/actions/detect-language-action@master
  java-findings:
    needs: define-language
    if: ${{ needs.define-language.outputs.language == 'Java'}}
    uses: Hotmart-Labs/backoffice-actions/.github/workflows/java-findings.yml@master
    with:
      runs-on: ${{ inputs.runs-on }}
  node-findings:
    needs: define-language
    if: ${{ needs.define-language.outputs.language == 'JavaScript/Node.js'}}
    uses: Hotmart-Labs/backoffice-actions/.github/workflows/node-findings.yml@master
    with:
      runs-on: ${{ inputs.runs-on }}


