name: Validator

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

concurrency: pipeline-define-language

jobs:
  java-findings:
    runs-on: ${{ inputs.runs-on }}
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Clone Application
        uses: actions/checkout@v3

      - name: Valid Hot Observability Java Finding
        uses: Hotmart-Labs/backoffice-actions/actions/valid-hot-observability-java-action@master

      - name: Valid Hot Observability Java Finding
        uses: Hotmart-Labs/backoffice-actions/actions/valid-hot-observability-java-action@master

